---

- hosts: all
  gather_facts: true
  become: true
  tasks:
   - ping: 
   - name: grdapi command
     set_fact:
      grdapi_command: ps -ef|grep java
      
      shell: grdapi_command >> test.log
      register: grdapi_command_op
      
      shell: cat test.log
      register: catop
      
      
   - name: print grdapi_command and cat
     debug: 
      var: grdapi_command_op
      var: catop
      
   - name: execute hostname
     command: hostname
     register: hostnameReg
     
   - name: print hostname 
     debug:
      var: hostnameReg
      
   - name: get the memtotalkb
     shell: cat /proc/meminfo
     register: meminfo
     
   - name: print meminfo
     debug: 
      var: meminfo
      
   - file:
      path: '/tmp/test'
      state: touch
