---

- hosts: all
  gather_facts: true
  become: true
  tasks:
   - name: grdapi command
     set_fact:
      grdapi_command: ps -ef|grep java
      shell: grdapi_command
      register: grdapi_command
      become: yes
      
   - name: print results
     debug: 
      var: grdapi_command
